# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [4]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [5]:
train = data.sample(frac=0.8, random_state=42)
test = data.drop(train.index) 
X_train = train.drop(columns=["MEDV"])
y_train = train["MEDV"]
X_test = test.drop(columns=["MEDV"])
y_test = test["MEDV"]

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [6]:
from sklearn import linear_model  # Import the linear_model module
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)# Your code here :

LinearRegression()

## 3. Calculate and print R-squared for both the training and the testing set.

In [7]:
from sklearn.metrics import r2_score
test_x_ = regr.predict(X_test)
print("R2-score: %.2f" % r2_score(y_test , test_x_))

train_x_ = regr.predict(X_train)
print("R2-score: %.2f" % r2_score(y_train , train_x_))
# Your code here :

R2-score: 0.69
R2-score: 0.75

## 4. Calculate and print mean squared error for both the training and the testing set.

In [8]:
import numpy as np
print("Residual sum of squares (MSE): %.2f" % np.mean((test_x_ - y_test) ** 2))
print("Residual sum of squares (MSE): %.2f" % np.mean((train_x_ - y_train) ** 2))# Your code here :

Residual sum of squares (MSE): 22.49
Residual sum of squares (MSE): 21.89

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [9]:
print("Mean absolute error: %.2f" % np.mean(np.absolute(test_x_ - y_test)))
print("Mean absolute error: %.2f" % np.mean(np.absolute(train_x_ - y_train)))# Your code here :# Your code here :

Mean absolute error: 3.18
Mean absolute error: 3.34

## Classification Model Evaluation

In [10]:
from sklearn.datasets import load_iris
data = load_iris()

In [11]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [12]:
column_names = data.feature_names

In [13]:
df = pd.DataFrame(data['data'],columns=column_names)

In [14]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [15]:
target = pd.DataFrame(data.target)

In [16]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [17]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [18]:
train = df.sample(frac=0.8, random_state=42)
test = df.drop(train.index) 
X_train = train
y_train = data.target[train.index]
X_test = test
y_test = data.target[test.index]

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [25]:
from sklearn.linear_model import LogisticRegression
X, y = load_iris(return_X_y=True)
lm = LogisticRegression()
lm.fit(X_train, y_train)
lm.predict(X_test)
lm.predict(X_train)
# Your code here :

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0,
       0, 1, 1, 2, 2, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1,
       1, 2, 1, 2, 0, 2, 1, 2, 1, 1])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [34]:
from sklearn.metrics import accuracy_score
acctrain = accuracy_score(y_train, lm.predict(X_train))
acctest = accuracy_score(y_test, lm.predict(X_test))

print(acctrain)
print(acctest)

# Your code here :

0.9833333333333333
0.9666666666666667

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [35]:
from sklearn.metrics import balanced_accuracy_score
baltrain = balanced_accuracy_score(y_train, lm.predict(X_train))
baltest = balanced_accuracy_score(y_test, lm.predict(X_test))

print(baltrain)
print(baltest)# Your code here :

0.982905982905983
0.9722222222222222

## 10. Calculate and print the precision score for both the training and the testing set.

In [39]:
from sklearn.metrics import precision_score
pretrain = precision_score(y_train, lm.predict(X_train), average='weighted') 
pretest = precision_score(y_test, lm.predict(X_test), average='weighted')

print(pretrain)
print(pretest)# Your code here :

0.9841666666666666
0.9694444444444444

## 11. Calculate and print the recall score for both the training and the testing set.

In [41]:
from sklearn.metrics import recall_score
rectrain = recall_score(y_train, lm.predict(X_train), average='weighted')
rectest = recall_score(y_test, lm.predict(X_test), average='weighted')

print(rectrain)
print(rectest)# Your code here :

0.9833333333333333
0.9666666666666667

## 12. Calculate and print the F1 score for both the training and the testing set.

In [43]:
from sklearn.metrics import f1_score
f1train = f1_score(y_train, lm.predict(X_train), average='weighted')
f1test = f1_score(y_test, lm.predict(X_test), average='weighted')

print(f1train)
print(f1test)# Your code here :

0.9833277103013944
0.9666666666666667

## 13. Generate confusion matrices for both the training and the testing set.

In [45]:
from sklearn.metrics import multilabel_confusion_matrix
conftrain = multilabel_confusion_matrix(y_train, lm.predict(X_train))
conftest = multilabel_confusion_matrix(y_test, lm.predict(X_test))

print(conftrain)
print(conftest)# Your code here :

[[[77  0]
  [ 0 43]]

 [[81  0]
  [ 2 37]]

 [[80  2]
  [ 0 38]]]
[[[23  0]
  [ 0  7]]

 [[18  1]
  [ 0 11]]

 [[18  0]
  [ 1 11]]]

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [26]:
# Have fun here !