# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [133]:
import pandas as pd
import warnings
from sklearn.linear_model import LinearRegression , LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,accuracy_score, classification_report, confusion_matrix, balanced_accuracy_score, precision_score,recall_score,f1_score
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [134]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [135]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [136]:
data.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [137]:
ind_vars = data[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT']]
medv = data["MEDV"]

ind_vars_train, ind_vars_test, medv_train, medv_test = train_test_split(ind_vars,medv,test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [138]:
medv_lr = LinearRegression()
medv_lr = medv_lr.fit(ind_vars_train, medv_train)

## 3. Calculate and print R-squared for both the training and the testing set.

In [139]:
R2_train = medv_lr.score(ind_vars_train,medv_train)
R2_test = medv_lr.score(ind_vars_test,medv_test)

print(R2_train,R2_test)

0.7554079932494925 0.6561680652958908

## 4. Calculate and print mean squared error for both the training and the testing set.

In [140]:
medv_pred_train = medv_lr.predict(ind_vars_train)
medv_pred_test = medv_lr.predict(ind_vars_test)

print(mean_squared_error(medv_train,medv_pred_train))
print(mean_squared_error(medv_test,medv_pred_test))

20.502056554541372
29.62222266633761

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [141]:
print(mean_absolute_error(medv_train, medv_pred_train))
print(mean_absolute_error(medv_test, medv_pred_test))

3.1993409335565657
3.5906445695361637

## Classification Model Evaluation

In [142]:
from sklearn.datasets import load_iris
data = load_iris()

In [143]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [144]:
column_names = data.feature_names

In [145]:
df = pd.DataFrame(data['data'],columns=column_names)

In [146]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
target = pd.DataFrame(data.target)

     0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

In [148]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [149]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [150]:
ind_vars = df
ind_vars

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [151]:
ind_vars_train, ind_vars_test, target_train, target_test = train_test_split(ind_vars,target,test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [152]:
isis_logr = LogisticRegression()
isis_logr = isis_logr.fit(ind_vars_train,target_train)

target_pred_train = isis_logr.predict(ind_vars_train)
target_pred_test = isis_logr.predict(ind_vars_test)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [153]:
train_acc = accuracy_score(target_train, target_pred_train)
test_acc  = accuracy_score(target_test, target_pred_test)

print(train_acc,test_acc)

0.975 0.9333333333333333

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [154]:
train_acc_bal = balanced_accuracy_score(target_train, target_pred_train)
test_acc_bal  = balanced_accuracy_score(target_test, target_pred_test)

print(train_acc_bal,test_acc_bal)

0.9736486486486488 0.9333333333333332

## 10. Calculate and print the precision score for both the training and the testing set.

In [ ]:
train_prec_macro = precision_score(target_train, target_pred_train, average='macro')
test_prec_macro  = precision_score(target_test, target_pred_test, average='macro')

print(train_prec_macro,test_prec_macro)

0.9744805781391147 0.9555555555555556

In [157]:
train_prec_weighted = precision_score(target_train, target_pred_train,average='weighted')
test_prec_weighted  = precision_score(target_test, target_pred_test,average='weighted')

print(train_prec_weighted,test_prec_weighted)

0.975175022583559 0.9422222222222222

## 11. Calculate and print the recall score for both the training and the testing set.

In [ ]:
train_recall_macro = recall_score(target_train, target_pred_train, average='macro')
test_recall_macro  = recall_score(target_test, target_pred_test, average='macro')

print(train_recall_macro,test_recall_macro)

In [ ]:
train_recall_weighted = recall_score(target_train, target_pred_train, average='weighted')
test_recall_weighted  = recall_score(target_test, target_pred_test, average='weighted')

print(train_recall_weighted,test_recall_weighted)

## 12. Calculate and print the F1 score for both the training and the testing set.

In [ ]:
train_f1_score_macro = f1_score(target_train, target_pred_train, average = "macro")
test_f1_score_macro  = f1_score(target_test, target_pred_test, average = "macro")

print(train_f1_score_macro,test_f1_score_macro)

In [ ]:
train_f1_score_weighted = f1_score(target_train, target_pred_train, average = "weighted")
test_f1_score_weighted  = f1_score(target_test, target_pred_test, average = "weighted")

print(train_f1_score_weighted,test_f1_score_weighted)

## 13. Generate confusion matrices for both the training and the testing set.

In [160]:
confusion_matrix_isis_train = confusion_matrix(target_train, target_pred_train)
confusion_matrix_isis_test = confusion_matrix(target_test, target_pred_test)

print(confusion_matrix_isis_train)

print(confusion_matrix_isis_test)

[[43  0  0]
 [ 0 39  1]
 [ 0  2 35]]
[[ 7  0  0]
 [ 0  8  2]
 [ 0  0 13]]

In [164]:

confusion_matrix_isis_train_df = pd.DataFrame(confusion_matrix_isis_train, index=data['target_names'] ,columns = data['target_names'])
confusion_matrix_isis_test_df = pd.DataFrame(confusion_matrix_isis_test, index=data['target_names'] ,columns = data['target_names'])

display(confusion_matrix_isis_train_df)
display(confusion_matrix_isis_test_df)

            setosa  versicolor  virginica
setosa          43           0          0
versicolor       0          39          1
virginica        0           2         35

            setosa  versicolor  virginica
setosa           7           0          0
versicolor       0           8          2
virginica        0           0         13

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [ ]:
# Have fun here !