# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [106]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [107]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [108]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [109]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [110]:
from sklearn.model_selection import train_test_split

X = pd.DataFrame(data, columns=['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'])
y = pd.Series(data["MEDV"])

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [111]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression() # Create the Linear Regression estimator
lr.fit(X_train, y_train) # Perform the fitting

# Prediction
y_test_pred = lr.predict(X_test)
y_train_pred = lr.predict(X_train)

## 3. Calculate and print R-squared for both the training and the testing set.

In [112]:
# evaluation
r2score_train = lr.score(X_train, y_train)
r2score_test = lr.score(X_test, y_test)

# The coefficient of determination: 1 is perfect prediction
print('R^2 Score for Training Set: {}'.format(r2score_train))
print('R^2 Score for Testing Set: {}'.format(r2score_test))

R^2 Score for Training Set: 0.7508856358979673
R^2 Score for Testing Set: 0.6687594935356301

## 4. Calculate and print mean squared error for both the training and the testing set.

In [113]:
from sklearn.metrics import mean_squared_error
mse_test = mean_squared_error(y_test, y_test_pred)
mse_train = mean_squared_error(y_train, y_train_pred)
# The mean squared error
print('\nMSE Testing Set: {}'.format(mse_test))
print('\nMSE Training Set: {}'.format(mse_train))

MSE Testing Set: 24.291119474973655

MSE Training Set: 21.641412753226312

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [114]:
#calculating the mean absolute error:
from sklearn.metrics import mean_absolute_error
mae_test = mean_absolute_error(y_test, y_test_pred)  
mae_train = mean_absolute_error(y_train, y_train_pred)
print('\nMean Absolute Error Testing Set: {}'.format(mae_test))
print('\nMean Absolute Error Training Set: {}'.format(mae_train))

Mean Absolute Error Testing Set: 3.1890919658878594

Mean Absolute Error Training Set: 3.314771626783229

## Classification Model Evaluation

In [115]:
from sklearn.datasets import load_iris
data = load_iris()

In [116]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [117]:
column_names = data.feature_names

In [118]:
df = pd.DataFrame(data['data'],columns=column_names)

In [119]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [120]:
target = pd.DataFrame(data.target)

In [121]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [122]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [123]:
X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [124]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression() # Create the Logistic Regression estimator
log_reg.fit(X_train, y_train) # Perform the fitting

# Prediction
y_test_pred = log_reg.predict(X_test)
y_train_pred = log_reg.predict(X_train)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [125]:
from sklearn.metrics import accuracy_score

acc_train = accuracy_score(y_train, y_train_pred)
acc_test = accuracy_score(y_test, y_test_pred)

print(f"Accuracy Train: {acc_train:.4f}")
print(f"Accuracy Test: {acc_test:.4f}")

Accuracy Train: 0.9750
Accuracy Test: 1.0000

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [126]:
from sklearn.metrics import balanced_accuracy_score

bal_acc_train = balanced_accuracy_score(y_train, y_train_pred)
bal_acc_test = balanced_accuracy_score(y_test,  y_test_pred)

print(f"Balanced Accuracy Train: {bal_acc_train:.4f}")
print(f"Balanced Accuracy Test: {bal_acc_test:.4f}")

Balanced Accuracy Train: 0.9756
Balanced Accuracy Test: 1.0000

## 10. Calculate and print the precision score for both the training and the testing set.

In [127]:
from sklearn.metrics import precision_score

pres_score_train = precision_score(y_train, y_train_pred,average="weighted")
pres_score_test = precision_score(y_test, y_test_pred,average="weighted")

print(f"Precision Score for Training Set: {pres_score_train}")
print(f"Precision Score for Testing Set: {pres_score_test}")

Precision Score for Training Set: 0.9767857142857144
Precision Score for Testing Set: 1.0

## 11. Calculate and print the recall score for both the training and the testing set.

In [128]:
from sklearn.metrics import recall_score

rec_score_train =  recall_score(y_train,y_train_pred,average="weighted")
rec_score_test =  recall_score(y_test,y_test_pred,average="weighted")

print(f"Recall Score for Training Set: {rec_score_train}")
print(f"Recall Score for Testing Set: {rec_score_test}")

Recall Score for Training Set: 0.975
Recall Score for Testing Set: 1.0

## 12. Calculate and print the F1 score for both the training and the testing set.

In [129]:
from sklearn.metrics import f1_score

print(f"F1 Score for Training Set: {f1_score(y_train,y_train_pred,average="weighted")}")
print(f"F1 Score for Test Set: {f1_score(y_test,y_test_pred,average="weighted")}")

F1 Score for Training Set: 0.9749882794186592
F1 Score for Test Set: 1.0

## 13. Generate confusion matrices for both the training and the testing set.

In [130]:
from sklearn.metrics import confusion_matrix

cm_train = confusion_matrix(y_train,y_train_pred)
cm_test = confusion_matrix(y_test,y_test_pred)

print(f"\nConfusion Matrix for Training Set:\n{cm_train}")
print(f"\nConfusion Matrix for Test Set:\n{cm_test}")

Confusion Matrix for Training Set:
[[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]

Confusion Matrix for Test Set:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [134]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import xgboost as xgb

# Define all models in a dictionary
models = {
    "Logistic Regression": LogisticRegression(),
    "KNN":                 KNeighborsClassifier(),
    "Decision Tree":       DecisionTreeClassifier(),
    "Random Forest":       RandomForestClassifier(),
    "SVM":                 SVC(),
    "XGBoost":             xgb.XGBClassifier(eval_metric='logloss')
}

# Loop through each model, train, predict and evaluate
for name, model in models.items():
    # Train
    model.fit(X_train, y_train)
    
    # Predict
    y_train_pred = model.predict(X_train)
    y_test_pred  = model.predict(X_test)
    
    # Metrics
    print(f"\n{'='*45}")
    print(f"Model: {name}")
    print(f"{'='*45}")
    print(f"Accuracy        — Train: {accuracy_score(y_train, y_train_pred):.4f} | Test: {accuracy_score(y_test, y_test_pred):.4f}")
    print(f"Balanced Acc    — Train: {balanced_accuracy_score(y_train, y_train_pred):.4f} | Test: {balanced_accuracy_score(y_test, y_test_pred):.4f}")
    print(f"Precision       — Train: {precision_score(y_train, y_train_pred, average='weighted'):.4f} | Test: {precision_score(y_test, y_test_pred, average='weighted'):.4f}")
    print(f"Recall          — Train: {recall_score(y_train, y_train_pred, average='weighted'):.4f} | Test: {recall_score(y_test, y_test_pred, average='weighted'):.4f}")
    print(f"F1 Score        — Train: {f1_score(y_train, y_train_pred, average='weighted'):.4f} | Test: {f1_score(y_test, y_test_pred, average='weighted'):.4f}")

=============================================
Model: Logistic Regression
=============================================
Accuracy        — Train: 0.9750 | Test: 1.0000
Balanced Acc    — Train: 0.9756 | Test: 1.0000
Precision       — Train: 0.9768 | Test: 1.0000
Recall          — Train: 0.9750 | Test: 1.0000
F1 Score        — Train: 0.9750 | Test: 1.0000

=============================================
Model: KNN
=============================================
Accuracy        — Train: 0.9667 | Test: 1.0000
Balanced Acc    — Train: 0.9671 | Test: 1.0000
Precision       — Train: 0.9675 | Test: 1.0000
Recall          — Train: 0.9667 | Test: 1.0000
F1 Score        — Train: 0.9667 | Test: 1.0000

=============================================
Model: Decision Tree
=============================================
Accuracy        — Train: 1.0000 | Test: 1.0000
Balanced Acc    — Train: 1.0000 | Test: 1.0000
Precision       — Train: 1.0000 | Test: 1.0000
Recall          — Train: 1.0000 | Test: 1.0000
F1 Score        — Train: 1.0000 | Test: 1.0000

=============================================
Model: Random Forest
=============================================
Accuracy        — Train: 1.0000 | Test: 1.0000
Balanced Acc    — Train: 1.0000 | Test: 1.0000
Precision       — Train: 1.0000 | Test: 1.0000
Recall          — Train: 1.0000 | Test: 1.0000
F1 Score        — Train: 1.0000 | Test: 1.0000

=============================================
Model: SVM
=============================================
Accuracy        — Train: 0.9750 | Test: 1.0000
Balanced Acc    — Train: 0.9752 | Test: 1.0000
Precision       — Train: 0.9752 | Test: 1.0000
Recall          — Train: 0.9750 | Test: 1.0000
F1 Score        — Train: 0.9750 | Test: 1.0000

=============================================
Model: XGBoost
=============================================
Accuracy        — Train: 1.0000 | Test: 1.0000
Balanced Acc    — Train: 1.0000 | Test: 1.0000
Precision       — Train: 1.0000 | Test: 1.0000
Recall          — Train: 1.0000 | Test: 1.0000
F1 Score        — Train: 1.0000 | Test: 1.0000

**Logistic Regression and SVM are the most trustworthy results here**, because:

-Their train score is below 1.0 (they didn't memorise the training data)

-Yet they still achieve 1.0 on test (they genuinely generalised)

Decision Tree, Random Forest, and XGBoost all scoring 1.0 on train is a sign of overfitting, they memorised every training sample. They happen to still score 1.0 on test because Iris is so simple, but on a harder real-world dataset this pattern would likely hurt their test performance.