# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [84]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd


from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score , accuracy_score
from sklearn.metrics import mean_absolute_error, median_absolute_error , balanced_accuracy_score
from sklearn.metrics import precision_score , recall_score
from sklearn.metrics import f1_score , confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [3]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [ ]:
# Your code here :
# Take all columns except MEDV
X = data.drop('MEDV', axis=1)
Y = data['MEDV'] 

# split into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.25,random_state=42,shuffle=True)

print(f"X_train Training Samples: {X_train.shape[0]}")
print(f"X_test Samples: {X_test.shape[0]}")
print(f"Y_train Training Samples: {Y_train.shape[0]}")
print(f"Y_test Training Samples: {Y_test.shape[0]}")

# @ AI : I just like this representation
print(f"Split: {len(X_train)} train ({len(X_train)/len(data):.1%}) | "
      f"{len(X_test)} test ({len(X_test)/len(data):.1%})")

X_train Training Samples: 379
X_test Samples: 127
Y_train Training Samples: 379
Y_test Training Samples: 127
Split: 379 train (74.9%) | 127 test (25.1%)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [11]:
# Your code here :

model = LinearRegression().fit(X_train,Y_train)
Y_train_predict, Y_test_predict = model.predict(X_train),model.predict(X_test)

print("Model trained successfully!")
print(f"Training predictions shape: {Y_train_predict.shape}")
print(f"Testing predictions shape: {Y_test_predict.shape}")
print(f"\nFirst 5 training predictions: {Y_train_predict[:5]}")
print(f"First 5 actual training values: {Y_train.iloc[:5].values}")

print(f"Intercept: {model.intercept_:.2f}")
print(f"Number of coefficients: {len(model.coef_)}")
print(f"\nTop3 Influential features:")
feature_importance = sorted(zip(X_train.columns,model.coef_),key=lambda x:abs(x[1]), reverse=True)[:3]
for feat, coef in feature_importance:
    print(f"{feat}:  {coef:.4f}")

Model trained successfully!
Training predictions shape: (379,)
Testing predictions shape: (127,)

First 5 training predictions: [33.7645899  19.7281695  38.92799377 14.41979559 25.01613817]
First 5 actual training values: [37.9 15.6 45.4 15.7 22.6]
Intercept: 29.84
Number of coefficients: 13

Top3 Influential features:
NOX:  -16.2388
RM:  4.3688
CHAS:  2.7735

## 3. Calculate and print R-squared for both the training and the testing set.

In [ ]:
# Your code here :

# R2 score for training data
r2_trainData = r2_score(Y_train,Y_train_predict)

#R2 score for testing data
r2_testData = r2_score(Y_test,Y_test_predict)

print("R2 Squared Results:")
print(f"Training R2: {r2_trainData:.4f}")
print(f"Testing R2:{r2_testData:.4f}")

# Verify the result from the R2 Data
if r2_trainData - r2_testData > 0.1:
    print("\n Warning : Large gap suggests overfitting!")
else:
    print("\n Model Generalizes well!")

R2 Squared Results:
Training R2: 0.7481
Testing R2:0.6844

 Model Generalizes well!

## 4. Calculate and print mean squared error for both the training and the testing set.

In [ ]:
# Your code here :

''' Mean Square value penalizes large errors MORE than others. As it measures the average squred difference betweeen measure and actual values.
'''
#  MSE for Training Data

mse_training = mean_squared_error(Y_train,Y_train_predict)

# MSE for test data 

mse_testing = mean_squared_error(Y_test, Y_test_predict)

# Show results 

print("Means Squared Error:")
print(f"Training MSE : {mse_training:.4f}")
print(f"Test Data MSE :{mse_testing:.4f}")

# Now interpret the data :

print("Root Mean Squared Error : For Interpretation ")
rmse_training = mse_training ** 0.5
rmse_testing = mse_testing ** 0.5

print(f"Training RMSE: ${rmse_training:.4f}")
print(f"Testing RMSE: ${rmse_testing:.4f}")

print(f"{'Metric':<15} {'Training':<12} {'Testing':<12}")

print(f"{'MSE':<15} {mse_training:<12.2f} {mse_testing:<12.2f}")
print(f"{'RMSE':<15} ${rmse_training:<11.2f}k ${rmse_testing:<11.2f}k")
print(f"\nAvg prediction error: ~${rmse_testing:.2f}k on unseen data")

Means Squared Error:
Training MSE : 22.3401
Test Data MSE :22.0987
Root Mean Squared Error : For Interpretation
Training RMSE: $4.7265
Testing RMSE: $4.7009
Metric          Training     Testing
MSE             22.34        22.10
RMSE            $4.73       k $4.70       k

Avg prediction error: ~$4.70k on unseen data

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [ ]:
# Your code here :

# Mean absolute error for Training data

mae_training = mean_absolute_error(Y_train,Y_train_predict)

# Mean absolute error for Test Data

mae_testing = mean_absolute_error(Y_test,Y_test_predict)

# Meadian Absolute error for Test Data

medAbs_testing = median_absolute_error(Y_test,Y_test_predict)

print("Mean absolute error")

print(f" Training Mean absolute error:${mae_training:.4f}k")
print(f" Test Mean absolute error:${mae_testing:.4f}k")
print(f"\n Interpretation: On Average, predictions are off by ${mae_testing:.2f}k")

print(f"MAE  (mean error):   ${mae_testing:.2f}k")
print(f"MedAE (median error): ${medAbs_testing:.2f}k")
print(f"Difference: ${abs(mae_testing - medAbs_testing):.2f}k", end="")
print(" (large diff = outliers present)" if abs(mae_testing - medAbs_testing) > 1 else " (no major outliers)")

Mean absolute error
 Training Mean absolute error:$3.3663k
 Test Mean absolute error:$3.0609k

 Interpretation: On Average, predictions are off by $3.06k
MAE  (mean error):   $3.06k
MedAE (median error): $2.12k
Difference: $0.94k (no major outliers)

## Classification Model Evaluation

In [33]:
from sklearn.datasets import load_iris
data = load_iris()

In [34]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [49]:
column_names = data.feature_names
column_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [59]:
df = pd.DataFrame(data['data'],columns=column_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [42]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [47]:
target = pd.DataFrame(data.target)
target

     0
0    0
1    0
2    0
3    0
4    0
..  ..
145  2
146  2
147  2
148  2
149  2

[150 rows x 1 columns]

In [50]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [51]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [85]:
# Your code here :

# Split the dataset using train_test_split

df_train_class, df_test_class, target_train_class, target_test_class  = train_test_split(df,target
                                                                                            ,test_size=0.25,
                                                                                            random_state=42,
                                                                                            stratify=target
)

print(f"Training Samples:{len(df_train_class)}")
print(f"Testing Samples:{len(df_test_class)}")
print(f"\n Class Distribution in training: ")
print(target_train_class.value_counts())
print(target_test_class.value_counts())

Training Samples:112
Testing Samples:38

 Class Distribution in training:
0
0    38
1    37
2    37
Name: count, dtype: int64
0
1    13
2    13
0    12
Name: count, dtype: int64

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [66]:
# Your code here :

# Create and Train Model
model_class = LogisticRegression(max_iter=1000,random_state=42)
model_class.fit(df_train_class,target_train_class)

# Generate Predictions

target_train_predict = model_class.predict(df_train_class)
target_test_predict = model_class.predict(df_test_class)

print(f"Logistical Regression trained successfully!")
print(f"Training Predictions:[{len(target_train_predict)}]")
print(f"Testing Prediction:{len(target_test_predict)}")
print(f"\nFirst 10 predictions:{target_test_predict[:10]}")
print(f"\nFirst 10 actual:{target_test_class[:10]}")

Logistical Regression trained successfully!
Training Predictions:[112]
Testing Prediction:38

First 10 predictions:[0 1 1 1 0 1 2 2 2 2]

First 10 actual:     0
42   0
56   1
99   1
53   1
38   0
85   1
134  2
141  2
107  2
132  2

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [ ]:
# Your code here :

#using Accuracy score function
accuracy_train = accuracy_score(target_train_class, target_train_predict)
accuracy_test = accuracy_score(target_test_class,target_test_predict)

print("Accuracy Scores")
print(f"Training Accuracy :{accuracy_train:.4f}({accuracy_train*100:.2f}%)")
print(f"Testing  Accuracy :{accuracy_test:.4f}({accuracy_test*100:.2f}%)")

Accuracy Scores
Training Accuracy :0.9732(97.32%)
Testing  Accuracy :0.9474(94.74%)

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [ ]:
# Your code here :

# Using Balanced accuracy score function

balanced_train = balanced_accuracy_score(target_train_class,target_train_predict)
balanced_test = balanced_accuracy_score(target_test_class,target_test_predict)

print("Balanced Accuracy Score :")
print(f"Training : {balanced_train:.4f}")
print(f"Test :{balanced_test:.4f}")

Balanced Accuracy Score :
Training : 0.9730
Test :0.9487

## 10. Calculate and print the precision score for both the training and the testing set.

In [ ]:
# Your code here :

# Using Precision Score function

precision_train = precision_score(target_train_class,target_train_predict, average='weighted')
precision_test = precision_score(target_test_class,target_test_predict, average='weighted')

print("Precision Accuracy")
print(f"Training Precision:{precision_train:.4f}")
print(f"Test Precision:{precision_test:.4f}")

Precision Accuracy
Training Precision:0.9734
Test Precision:0.9474

## 11. Calculate and print the recall score for both the training and the testing set.

In [ ]:
# Your code here :

# Using Recall Score function

recall_train = recall_score(target_train_class,target_train_predict,average='weighted')
recall_test = recall_score(target_test_class,target_test_predict,average='weighted')

print("Recall Score")
print(f"Training Recall:{recall_train:.4f}")
print(f"Test Recall:{recall_test:.4f}")

Recall Score
Training Recall:0.9732
Test Recall:0.9474

## 12. Calculate and print the F1 score for both the training and the testing set.

In [ ]:
# Your code here :

# using F1 Score function
f1_training = f1_score(target_train_class,target_train_predict,average='weighted')
f1_testing = f1_score(target_test_class,target_test_predict, average='weighted')

print("F1 Score")
print(f"Traing F1 Score:{f1_training:.4f}")
print(f"Test F1 Score:{f1_testing:.4f}")

F1 Score
Traing F1 Score:0.9732
Test F1 Score:0.9474

## 13. Generate confusion matrices for both the training and the testing set.

In [83]:
# Your code here :

confMat_training = confusion_matrix(target_train_class,target_train_predict)
confMat_test = confusion_matrix(target_test_class,target_test_predict)

print("Confusion Matrix : Training Set")
print(confMat_training)
print("\nConfusion Matrix : Test Set")
print(confMat_test)

# Interpretation :

print("\n Interpretation (Test Set):")
print("Diagonal Values = correct predictions")
print("Off-Diagonal = Misclassificaitons ")

print(f"Total correct : {confMat_test.diagonal().sum()}")
print(f"Total Wrong : {confMat_test.sum() - confMat_test.diagonal().sum()}")

Confusion Matrix : Training Set
[[38  0  0]
 [ 0 35  2]
 [ 0  1 36]]

Confusion Matrix : Test Set
[[12  0  0]
 [ 0 12  1]
 [ 0  1 12]]

 Interpretation (Test Set):
Diagonal Values = correct predictions
Off-Diagonal = Misclassificaitons
Total correct : 36
Total Wrong : 2

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [ ]:
# Have fun here !

# Here i just do the basic 


models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'SVM': SVC(random_state=42)
}

print("Model Comparison (Testing Set Accuracy):")
for name, model in models.items():
    model.fit(data_train_class, target_train_class)
    accuracy = model.score(data_test_class, target_test_class)
    print(f"  {name:20s}: {accuracy:.4f}")

Model Comparison (Testing Set Accuracy):
  Logistic Regression : 0.9474
  Decision Tree       : 0.8947
  Random Forest       : 0.9211
  SVM                 : 0.9211